### ISSUE TITLE
A few things

### ISSUE THREAD

**Issue by cheezitbomb** [Bunsan/TechNodeFirmaCraft#1]
First it seems like mekanism Enriched Alloy can only be made with minecraft iron ingots which the only way to get from what NEI shows is by smelting minecraft iron ore. Someone else and I from looking around found one way to get it but I was unsure if you planed it as only getting it that way or if you had intended for it to be changed to wrought iron in the recipe.

One person was having trouble with placing the planks you get from a saw and logs, whenever they placed the planks it caused them to get disconnected. They said it only happened in multiplayer. I haven't been able to recreate this myself.

When trying to place two fence gates down next to each other it crashes my client out(I believe this may be something with TFC itself).

When switching from single player to multiplayer the client gets an error

> Connection Lost
> A fatal error has occured, this connection is terminated

Server console spams this while trying to connect

> [16:43:19] [Netty IO #1/ERROR] [FML]: NetworkDispatcher exception 
> java.io.IOException: Broken pipe
> at sun.nio.ch.FileDispatcherImpl.writev0(Native Method) ~[?:1.7.0_71]
> at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51) ~[?:1.7.0_71]
> at sun.nio.ch.IOUtil.write(IOUtil.java:148) ~[?:1.7.0_71]
> at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:524) ~[?:1.7.0_71]
> at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:249) ~[NioSocketChannel.class:?]
> at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:680) [AbstractChannel$AbstractUnsafe.class:?]
> at >io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:26>6) [AbstractNioChannel$AbstractNioUnsafe.class:?]
> at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:488) [NioEventLoop.class:?]
> at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
> at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
> at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) >[SingleThreadEventExecutor$2.class:?]
> at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]

ends with this

> [16:43:19] [Server thread/INFO]: cheezitbomb lost connection: >TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: >java.io.IOException: Broken pipe], siblings=[], style=Style{hasParent=false, color=null, bold=null, >italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
> [16:43:19] [Server thread/INFO]: cheezitbomb left the game

Restarting the client allows connection to multiplayer. So going from single player to multiplayer requires restarting client.

**Comment by Bunsan** [comment]
In future please log each issue separately and put crash reports in a pastebin.

My custom enriched iron and enriched alloy recipes seem to be missing. I'll need to redo those. There may be a few machine recipes missing I'll double check. 

I'll look into the gate and lumber issue. I don't have a test server set up yet so I'll have to get one up.

The disconnect on swapping from SSP to SMP I don't believe is pack specific. I'll try and see if I can find what could be causing this.

Thanks for reports.

**Comment by Bunsan** [comment]
Stupid phone.

**Comment by Bunsan** [comment]
The broken pipe crash is a vanilla issue. https://bugs.mojang.com/plugins/servlet/mobile#issue/MC-34947

I can't repeoduce the gate crash, could you explain the way to reproduce and if the is no crash log in your crash reports folder could you provide the console log. Log in, cause crash and stick the console info in a pastebin.

**Comment by Bunsan** [comment]
Recipe Fix in commit f2c1803b96
