### ISSUE TITLE
Unable to find reeds in the world.

### ISSUE THREAD

**Issue by cheesealmighty** [Bunsan/TechNodeFirmaCraft#11]
Hello,

Great modpack so far, yet I have a slight problem. I disabled forestry and pneumaticcraft to decrease the load on my hunk o' junk, which is my PC. Umm, but I tried in SMP (A dedicated server that I rented and set) and SSP with few seeds yet can't find any reeds anywhere. Yes I am checking the swamps, yet I've traveled 2000 blocks in each direction, enough to see rock type change. I am seeing ridiculous amounts of cat tails though, if that's relevant, or am I supposed to use them somehow? I did find TFC sugarcanes, but you know, those are not used for paper.  

I did fiddle with some of the TFC configs, but those were just to make ores more valuable, so don't spend as much time digging holes. Torches burn longer, pit kilns take less them and so on. Nothing related to terrain generation. And I didn't add any mods related to terrain generation. Here's the mods that I added: http://imgur.com/zxJpclm
Last four were added after terrain generation, hell, on the SMP last 7-8. And yes, I am using optifine, but I don't think that's relevant, and server weren't using optifine after all.

On a complete different side note, I can't seem to figure out how to combine ores into tabula rasa items(ie. ore piles, dusts, crystals), so that they can be processed in mekanism/immersive engineering machines. I don't see any recipes in NEI. Am I missing something? Or is it that you just didn't add the recipes yet? 

I am aware it is a painstaking process and really appreciate what you do <3 But yeah, I'll be happy to supply with further info if needed. (Also, if this is unrelated to you, I can post this on TFC issues, if that's the case, sorry for bothering you)

Best regards.

**Comment by cheesealmighty** [comment]
I can simply solve the problem by spawning the bloody things, but you know, rather have them the non-cheaty way.

**Comment by Bunsan** [comment]
The reeds do spawn, they are TFC and can just be rare. Southern areas have better luck. But I can say they are spawning as intended. 

As for of the other mods effected. I doubt it, but can't say for certain. 

The piles are craftable 4 poor with hammer make a pile. 2 normal with hammer make a pile. 1rich with hammer makes 3 poor. These recipes will negate your ore value buff as they are made based on my design. My ore values are already much higher than default.
