### ISSUE TITLE
Crash on shift clicking seeds from chest

### ISSUE THREAD

**Issue by ADKaster** [Bunsan/TechNodeFirmaCraft#19]
I got the following crash while mucking about my chests. There was a recent Terrafirmacraft update though, so maybe it was fixed there. I had just salted some beef, but the crash happened shift clicking some carrot seeds. 

http://pastebin.com/Y9tgGxeJ

**Comment by Bunsan** [comment]
TFC has just updated and the update does fix quite a few obscure crashes. We'll be updating once the ATLauncher server (currently having issues) is up again. Please let me know if you can reproduce the bug then. I would need a lot more information to try and replicate it myself. SSP or SMP? Single or double chest? Clicking in or out? I'm guessing it is some odd interaction with Inventory Tweeks.

**Comment by Bunsan** [comment]
Please reopen if you experience this bug again. I've not been able to replicate this in current or past builds.
