### ISSUE TITLE
Suggestion for Mod: Ships Mod by Cuchaz

### ISSUE THREAD

**Issue by soulslayer32** [Bunsan/TechNodeFirmaCraft#21]
Hey, I love the mod pack and i've had a bunch of fun with it. I was wondering if you guys could look into adding ships. This mod seems pretty good and realistic. https://www.cuchazinteractive.com/ships/

Thanks

**Comment by Bunsan** [comment]
This mod crashes with TFC TEs, such as chests, barrels etc. it is not stable enough to include.
