### ISSUE TITLE
Electrical Age

### ISSUE THREAD

**Issue by soulslayer32** [Bunsan/TechNodeFirmaCraft#27]
Hey, so i was wondering if you thought about adding electrical age to the mod pack. I think it would be a nice addition. i understand its a major mod pack so you might not want to include it, but i wanted to ask.

**Comment by Bunsan** [comment]
It is actually the reason that I have scheelite(is a tungsten ore) in the worldgen as I wanted to keep the door open for inclusion in the pack. It is something I plan to revisit soon, but it won't be a possibility for the next few updates.

**Comment by soulslayer32** [comment]
Oh so if you did add it, there would be no need to regen the world?

**Comment by Bunsan** [comment]
Yes that was the plan.

**Comment by ChaosTherum** [comment]
Is there anything stopping you from adding it or is it just time constraints. I was thinking of adding it in myself to practice my minetweaker skills.

**Comment by Bunsan** [comment]
Sorry for late reply. I'm not aware of any specific issues that would prevent this being integrated into the pack. My main concern would be balance and integration as far as working with other mods in pack. The one thing I was unsure of what the look and feel being quite separate from the rest of the pack. By all means have a crack at integrating it. If you have success let us know and we can look at integration with your work. If you run into problems feel free to come ask for help or to run ideas/solutions by us on IRC.
