### ISSUE TITLE
Mo quests, mo problems.

### ISSUE THREAD

**Issue by ReeloyJ** [Bunsan/TechNodeFirmaCraft#33]
Didn't see this logged in here, so I'll leave a few I've seen with the new HQM quests. looks great otherwise though.  

Casting Age - Sandiches: (Sandwiches not being recognised (tried with cornmeal bread) likely a similar issue to the old stone hoe issue
Stone Age - Salad Bar: (as above)
Casting Age - Bronze: Quest says "any will do" but doesnt accept bis.bronze likely the same issue.

As a side note/suggestion, I'm not sure if sylvite is a balanced reward for making a sandwich. Almost feels too easy. Maybe some cheese or treated meat instead?

**Comment by Bunsan** [comment]
I'll look into those. I think I know why. As for the rewards. The way TFC handles the food and decay makes food rewards impossible at the moment.

**Comment by Bunsan** [comment]
Sandwiches and Salads are fixe in version 2.7, Bronze is waiting on new HQM sadly.

**Comment by Bunsan** [comment]
All fixed as of 2.7
