### ISSUE TITLE
Immersive Engineering quests broken.

### ISSUE THREAD

**Issue by pagr** [Bunsan/TechNodeFirmaCraft#34]
All quests after Treated Wood and Engineers Workbench unlock and only contain the text Unnamed quest. Chapters after, such as forestry, remain closed even after completing all prior quests. The issue does not resolve using /hqm edit.

**Comment by Bunsan** [comment]
As stated on first page the quests are still a work in progress. We released them as the TFC portion was a steep learning curve for many new players. 

The quests were reworked for the last update. We are hoping aziel13 will get a chance to complete more quest pages soon.
