### ISSUE TITLE
Error on Startup.

### ISSUE THREAD

**Issue by elfishii** [Bunsan/TechNodeFirmaCraft#45]
Trying to start a server from BisectHosting and had them install the pack for me and it refuses to start. I was told to contact the Pack author saying it's their error. 
http://pastebin.com/xrSDjgZG
This is the console from me trying to start the server and it crashing.

**Comment by Bunsan** [comment]
I need a crash report please. The server log does not give me the information to figure out what they are doing wrong. 

As multiple servers are running the pack without issue, including our official server. So that suggests user error.

**Comment by Bunsan** [comment]
No follow up. Closing.
