### ISSUE TITLE
Bug with Portable Tanks

### ISSUE THREAD

**Issue by krwminer** [Bunsan/TechNodeFirmaCraft#5]
I am running your current Beta 2.0 files on a private server with friends. We can't wait for the final release. 

But I noticed a bug with the Portable Tank. If you right click a TFC barrel with the tank in hand it will transfer the liquid to the barrel but not remove it from the tank. So you basically can infinite fill your barrels with it.

You might able to prevent this through the use of the TechNodeFirmaCraft mod. I am one of the devs for MyTown protectections. Did you want me to submit a PR for it?

Also do you want me to throw up some other problems we have found here on the issues?

Lastly, is there a way to get access to your ATLauncher Dev builds directly? I have used the XMLs to figure out what you are using, but it would be nice to have a more direct access to it if you allow it.

**Comment by Bunsan** [comment]
Yes please submit any issues you have, it would be greatly appreciated. As for the barrels, I'm sure a PR would be useful, my collaborator deals with that as I'm not a programmer. If you can pop on the technode IRC that would probably be the easiest way. I can also get your IGN and put you in the Tester group for access to dev build.

**Comment by AnodeCathode** [comment]
We've disabled interaction between OpenBlocks tanks, Mek portable tanks and the barrels and vessels via the TNFC mod. Thanks.
