### ISSUE TITLE
Add Leather Water Sac?

### ISSUE THREAD

**Issue by chogata** [Bunsan/TechNodeFirmaCraft#50]
Hello,

Did you think about adding Leather Water Sac to the modlist?

TNFC is all about advancing in technology far more than pure TFC allows. It feels stupid that I can have a wind mill and electrical machines, but I still need to drink water from breakable jugs...

If you feel the sacs are too easy to obtain, change the recipe, but it would be a really great add-on.

**Comment by Bunsan** [comment]
Already queued up for next update.
