### ISSUE TITLE
No recipe for Weather Machine (needed for Weather Deflector)

### ISSUE THREAD

**Issue by fluffle** [Bunsan/TechNodeFirmaCraft#52]
I can see in Weather2.zs that you remove all the recipes, but the one you add for the Weather Deflector depends on a machine you don't add a new recipe for. Tornados are making me sad :-(

**Comment by Bunsan** [comment]
Those are intentionally uncraftable. If you wish to craft them you'll need to write your own recipe.

**Comment by fluffle** [comment]
Ah, OK, thanks. I have to ask, though: why bother adding a new recipe for the weather detector at all if it's supposed to be intentionally uncraftable?

**Comment by Bunsan** [comment]
Yeah not sure why there was a recipe added. Probably a relic of an old version that was forgotten. I've removed it for next update.
