### ISSUE TITLE
Changing game mode seems to break metal press

### ISSUE THREAD

**Issue by Tommyfacette** [Bunsan/TechNodeFirmaCraft#53]
Hello ! I just started a new solo world and randomly spawn in a huge canyon, active cheat fly out and keep continue. Well later when i build metal press from immersive engineering, it's taking power but don't works. So, i make some test in creative world and works perfectly and switching to survival in this test world and same; things don't work anymore. Weird ...

**Comment by Bunsan** [comment]
I haven't been able to replicate. I frequently swap between survival and creative in testing and have had no problems with metal press.

**Comment by Tommyfacette** [comment]
Ok, thanks i don't understand what append to my minecraft ... But it's
seems since the last update the bug is gone so thanks for your time.
And sorry for that.

2016-05-03 19:36 GMT+02:00 Bunsan notifications@github.com:
