### ISSUE TITLE
Can't place gems on blocks

### ISSUE THREAD

**Issue by Gskartwii** [Bunsan/TechNodeFirmaCraft#54]
The [Decorations addon](http://terrafirmacraft.com/f/topic/7694-tfc-07923-decorations-addon-for-tfc/) has a feature where you can place gems on a block for a light source. This however seems to be broken; right-clicking on a block while holding a gem simply does nothing.

**Comment by Bunsan** [comment]
Yes the feature uses a method that breaks recipes and NEI. So it is disabled on purpose.
