### ISSUE TITLE
OpenComputers Raw Circuitboard Recipe Requires Un-craftable Vanilla Clay Block

### ISSUE THREAD

**Issue by LarsonPacific** [Bunsan/TechNodeFirmaCraft#55]
Or is there some alternative way of creating vanilla clay blocks?

**Comment by Bunsan** [comment]
Fixed for next update.

**Comment by LarsonPacific** [comment]
Also, the tier 2 computer case requires a vanilla chest, and a tier 3 case requires a tier two case. Would you be able to look at the tier 2 recipe as well please? Thank you Bunsan :) Am loving the modpack!

**Comment by Bunsan** [comment]
Fixed. Thanks for reports. Glad you are enjoying pack.
