### ISSUE TITLE
Food Duplication

### ISSUE THREAD

**Issue by Maxwell-lt** [Bunsan/TechNodeFirmaCraft#57]
When crafting food in the Steve's Workshop crafting block, the NBT of the food gets messed up, letting you get huge amounts of food from the smallest piece.

Steps to reproduce:
1. Place any food item into a Steve's Workshop crafting table, with a (Vanilla Minecraft) crafting table in the upgrade slot.
2. Take the food item out of the crafting output. This food will not have a weight, and may have an erratic decay speed. If the food you are duplicating is cooked (I have not tested other forms of processing), this food will revert to the base version.
3. Now, in your inventory, place the food item into your crafting grid.
4. In the output, you should see a full, 160oz piece of food. There are actually several maximum size pieces and a smaller piece that you can take out, either by clicking and dragging each piece individually, or you can just shift-click on the output slot to get them all at once.
5. Now you have taken any size piece of food, and created several maximum size and a smaller piece of the base, unprocessed food.

Using version 2.16.4

**Comment by Bunsan** [comment]
I'll look to see if there is anything I can do to fix this. The issue is that TFC has its own food crafting handler that only works in player crafting grid.

**Comment by Maxwell-lt** [comment]
I just tested, and this bug is present when using the vanilla Minecraft crafting table as well.

**Comment by Bunsan** [comment]
I have a solution of sorts for the issue. Just seeing I can find a more elegant solution.

**Comment by Bunsan** [comment]
Best solution available was implemented for Update 2.17.
