### ISSUE TITLE
Metal Press not accepting blank molds

### ISSUE THREAD

**Issue by hexicles** [Bunsan/TechNodeFirmaCraft#58]
The metal press doesn't do anything with blank molds, neither right clicking or shift clicking works.( in version 2.16.4 )

**Comment by Bunsan** [comment]
The blank mold is an ingredient and doesn't go on the metal press. You place the item on the press and drop blank mold on belt. Tool heads must be processed in blast furnace to strip the nbt data before they can be placed on metal press.
