### ISSUE TITLE
Metal press mold for Decorations lantern core?

### ISSUE THREAD

**Issue by fluffle** [Bunsan/TechNodeFirmaCraft#59]
It's got to the point where I would like to be able to churn out a reasonable amount of power-free lighting for a wide area. Would it be possible to add a metal press mold for lantern cores?

**Comment by fluffle** [comment]
While I'm on the topic of molds, is it deliberate that black steel shears can't be pressed with a shears mold?

**Comment by Bunsan** [comment]
It is deliberate that the blacks steel shears not be craftable win press. The lantern cores are added for next update in commit 5d050c4.
