### ISSUE TITLE
Suggestion: Add Localized Weather & Stormfronts Mod

### ISSUE THREAD

**Issue by krwminer** [Bunsan/TechNodeFirmaCraft#6]
We have been adding this mod and it adds a lot to your modpack. We did end up disabling the damage from Tornadoes and Cyclones as it made the start really hard because of all the one time spawn stuff like animals and fruit trees were being killed off. It is just one config setting.

http://www.coros.us/mods/weather2

**Comment by Bunsan** [comment]
I had looked at this previously, but it's changes to weather prevented the gathering of rain in barrels and the forestry rain tank. We will look at it again, because it is a feature we'd like to have.

**Comment by krwminer** [comment]
It might work properly if you set in the config:

B:Misc_takeControlOfGlobalRain=false

From the web page:

"To make it more compatible with mods that need vanilla weather, enable global overcast mode in EZ GUI."

Although I really like the localized weather patterns.

**Comment by Bunsan** [comment]
Added in commit 2be91373cf
