### ISSUE TITLE
Item duplication

### ISSUE THREAD

**Issue by chogata** [Bunsan/TechNodeFirmaCraft#61]
If you craft with a TFC tool (saw, chisel) sometimes the tool duplicates. Happend after the 2.20 upgrade, on official server.

I cut bamboo with saw and I got extra 8 saws (same damage as the original one). See here: https://postimg.org/image/l6xmq94up/

Somebody mentioned having similar experience with chisel.

**Comment by AnodeCathode** [comment]
Fixed.
