### ISSUE TITLE
Osmium not melting in crucible

### ISSUE THREAD

**Issue by chogata** [Bunsan/TechNodeFirmaCraft#65]
Osmium is not melting in a crucible (I used coal and bellows a lot, WAILA said the crucible was brilliant white for a long time). I tried to melt all kinds of ore (normal, poor and rich) and ingots. Tried in 3.3 and 3.4

**Comment by Bunsan** [comment]
You need to use the coal coke dust in the forge to get it hot enough to melt osmium. From changelog to get the TFC coke. "Added Coal Pile. Functions like log pile and can be used in Coal Coke Pit, like Charcoal Pit. Coal Piles must be full. Coke Blocks must be broken with hammer. Will drop variable number of coke dust items."

**Comment by chogata** [comment]
Okay. But the description in NEI is misleading, as it shows only Brilliant White, same as iron or steel, that do not require coal coke dust to melt.
Maybe add another level of heat? Briliant White with stars or Blinding White? Or some kind of indicator in NEI? Because otherwise I feel lots of people are gonna fall into this trap ;)

**Comment by Bunsan** [comment]
I'm not going to fork the NEI plugin to change how it is displayed. It is what it is.
