### ISSUE TITLE
Making string with Bees

### ISSUE THREAD

**Issue by Aaronycaro25** [Bunsan/TechNodeFirmaCraft#69]
I have recently been playing this pack with friends and have started Bees in order to make string.   we got the silk wisps but when you try to craft the string it is removed right after.   wondering if this is intended if so why not remove the recipe or just a crafting bug

**Comment by Bunsan** [comment]
I figured out the issue in the scripts. I've actually got a bunch of fixes and such pending so I'm actually just going to push out an update.

**Comment by Bunsan** [comment]
Update with fix pushed.
