### ISSUE TITLE
Attempting to craft bibliocraft potion shelf

### ISSUE THREAD

**Issue by Knigge** [Bunsan/TechNodeFirmaCraft#71]
Thanks for fixing more of the issues, even when the pack is dormant. I'm listing a few issues in the chance that you some time later will want to fix even more:)

When attempting to craft the potion shelves from bibliocraft that have the tfc lumber and planks fixed, the glass bottle that I suspect is supposed to be in the midle of the crafting grid, is in fact Minecraft fire (Fire 51). As the slabs in the other recipe is impossible to craft, and fire is unobtainable. these recipes will be unaccessible to the player to craft.

**Comment by Bunsan** [comment]
I have a fix for this. I'll likely push it in the next few days.

**Comment by Bunsan** [comment]
fixed in 5451942
