### ISSUE TITLE
TFC Sugar quantity

### ISSUE THREAD

**Issue by Knigge** [Bunsan/TechNodeFirmaCraft#72]
When refining the TFC sugar canes into Sugar, the resulting amount of sugar is multiplied by 0.1, resulting in the already hard to come by Sugar to be even more unobtainable for the potion needs.

160Oz Sugar will need 1600Oz Sugar Cane, to be able to craft a 4000mb regen potion. Is this intentional?

**Comment by Bunsan** [comment]
This is just base TFC. I won't be changing it. Besides the regen potion is very powerful.
