### ISSUE TITLE
Clay vessel (large and small) -food storage

### ISSUE THREAD

**Issue by Knigge** [Bunsan/TechNodeFirmaCraft#73]
Thanks for fixing more of the issues, even when the pack is dormant. I'm listing a few issues in the chance that you some time later will want to fix even more:)

When attempting to make a more viable food storage, without TFC Cellars, using the small clay vessels to store food requires you to cut the pieces down to 80Oz to fit. This gets rather tedious in time, I suggest making storage of 160Oz pieces possible in these, or even better: Make large vessels have the same decay modifier as the smaller clay vessels.

Having the large vessels also reduce decay would make rooms like this more neccessary:
https://i.imgur.com/QjRo51A.png

**Comment by Bunsan** [comment]
I won't be changing TFC code to change this. Large vessels are a different class than small vessels and so would require a major rewrite to make them function like that.

**Comment by Aaronycaro25** [comment]
There is a scale and weights that can be made that makes cutting food very simple
