### ISSUE TITLE
Jack'o lanterns

### ISSUE THREAD

**Issue by Knigge** [Bunsan/TechNodeFirmaCraft#74]
The ability to create small nooks with a saw of jack'o lanterns is a well known and liked 'feature' of tfc to create permanent light.

If it is not possible or wanted to remove this, could a feature that makes the lanterns extinguish themselves after a set amount of time, like torches be possible? 

The ability to make these, greatly diminishes the need to actually make use of the great amount of other light sources your pack provides.

**Comment by Bunsan** [comment]
There is a bug in the microblocks code that doesn't allow us to blacklist jack'o lanterns or glowstone. My view has always been if you don't like them don't use them. I choose not to use them in any of my playthroughs. Folks using does not harm others and it is just a part of TFC. I don't want to go in and change them in the TFC code.

If you don't want them used on your server you can add this line of code into the  scripts/tfc.zs file recipes.remove(<terrafirmacraft:LitPumpkin>);
