### ISSUE TITLE
Power Generation and the prevalence of windmills

### ISSUE THREAD

**Issue by Knigge** [Bunsan/TechNodeFirmaCraft#75]
A min-maxing gameplay style will allow players to simply build skyblocks and set a wast amount of windmills on top of them to gain the cheapest amount of power. This dissuades the player from taking other pathways to surplus energy. Could both Mekanism and Immersive Engineering windmills provide a diminishing return for other windmills in the same general area, chunk or vicinity of each other?

**Comment by Bunsan** [comment]
I don't think they are a big issue. Watermills are by far more powerful. This is what it is. There is no obligation to use such methods and a player doing so is not harming others.
