### ISSUE TITLE
Smelting aluminium

### ISSUE THREAD

**Issue by unforbidable** [Bunsan/TechNodeFirmaCraft#80]
I have been failing to smelt a bunch of bauxite in the crucible, wondering if I am just not spamming the bellows hard enough. It just wouldn't melt. 

It seems that since 3.7 "Aluminium can no longer be processed in pit kiln". Can I still do it with Crucible/Forge or do I need steel furnace or possibly arc furnace? I think previously when I played I somehow owned aluminium ingots prior to arc furnace but I could be wrong.

I have been using TNFC coke dust, managed to smelt Tungsten (which realistically has got a much higher melting point compared to aluminium but I don't know how it works in game), so I assume my forge works.

Of course I understand if aluminium is harder to smelt for the sake of progression, and I am enjoying the way progression works in this mod pack. At this point I am just looking into crafting IE's redstone breaker which unfortunately but somewhat understandably takes HV relays to make.

Thank you and cheers!

https://imgur.com/AjH6ED5
https://imgur.com/fwpOeV3

**Comment by Bunsan** [comment]
This is intended. Bauxite was only suppose to be processed in the arc furnace. It was never able to be processed in the crucible and the pit kiln processing was unintended. Aluminium ingots etc. can be melted in crucible. This is for progression and is like real life. Processing aluminium from ore is very challenging, but melting pure aluminium is easy. There is a config option in TFCConfig to allow processing in the crucible if you really dislike it.

**Comment by unforbidable** [comment]
Ah, makes sense, thanks for the explanation and suggestion. Must have been using pit kiln previously. Note NEI shows bauxite as accepted in crucible.
