### ISSUE TITLE
Coke coal

### ISSUE THREAD

**Issue by Rudgher** [Bunsan/TechNodeFirmaCraft#81]
In the HQM Casting age questline there is a task to get coal/coke, but I cannot get regular coal and make holes with it, because NEI shows that to get it you need at least a crusher, or an error in choosing age or I have a bug, I don’t I can get coal without Railcraft / IE crusher
p.s sorry for my english

**Comment by Bunsan** [comment]
The quest is for charcoal. You get this by creating a TFC charcoal pit. There is a description in the quest book how to do this. The quest only triggers with charcoal. Also know that the bituminous coal and lignite drop minecraft coal when mined.
